# Site settings
title: intergalactic programming
name: haze
email: admin@haze.pw
description: Yet Another Programming Blog
baseurl:
url: https://haze.pw
twitter_username:
github_username:
disqus_username:

google-analytics: 
skillstree: true

# Build settings
permalink: none
markdown: kramdown
